---
- when: ansible_os_family == "Debian"
  block:
  - name: prepare (download the pkg)
    get_url:
      url: "https://github.com/tinygo-org/tinygo/releases/download/v{{ devcore_tinygo_version }}/{{ devcore_tinygo_file_name }}"
      dest: "/tmp/{{ devcore_tinygo_file_name }}"
  - name: install tinygo
    apt:
      deb: "/tmp/{{ devcore_tinygo_file_name }}"
    become: yes
- when: ansible_system == "Darwin"
  block:
  - community.general.homebrew_tap:
      name: tinygo-org/tools
  - homebrew:
      name: "tinygo"
