---
- name: Install pip3 packages
  pip:
    name: "{{ item }}"
    executable: pip3
  loop: "{{ devcore_python3_pip_pkgs }}"
- name: Install poetry with recomended process
  shell: |
    curl -sSL https://install.python-poetry.org | \
    python3 /dev/stdin -y
