---
- name: fetch tmux-xpanes
  get_url:
    url: https://raw.githubusercontent.com/greymd/tmux-xpanes/master/bin/xpanes
    dest: /tmp/xpanes
  when: ansible_system == 'Linux'
- name: install tmux-xpanes
  shell: |
    install -m 0755 xpanes {{ utils_tmux_xpane_dir }}/bin/xpanes
    echo "Ref: https://github.com/greymd/tmux-xpanes"
  args:
    chdir: /tmp/
  when: ansible_system == 'Linux'
- name: Install support tools
  apt:
    name: "{{ item }}"
  # loop: [ peco, direnv, fzf, tmux, tmuxinator, bat, jq, vim, exuberant-ctags, global ]
  loop: [ curl, peco, direnv, fzf, tmux, tmuxinator, jq, vim, exuberant-ctags, global ]
  # when: ansible_distribution == 'Ubuntu'
  when: ansible_os_family == 'Debian'
  become: yes
- name: Install support tools
  homebrew:
    name: "{{ item }}"
  loop: [ curl, peco, direnv, fzf, tmux, tmuxinator, tmux-xpanes, bat, jq, vim, ctags, global ]
  when: ansible_system == 'Darwin'
# tasks file for dev_utils
