---
- name: install golang
  ansible.builtin.get_url:
    url: "{{ devcore_go_url }}"
    dest: "{{ ansible_env.HOME }}/"
- name:
  ansible.builtin.unarchive:
    dest: "{{ devcore_go_home }}"
    src: "{{ ansible_env.HOME }}/{{ devcore_go_asset }}"
    remote_src: true
- name: "Make directories for '~/dev' as $GOPATH"
  file:
    path: "{{ item }}"
    state: directory
  loop:
  - "{{ devcore_go_gopath }}"
  - "{{ devcore_go_gopath }}/bin"
  - "{{ devcore_go_gopath }}/src"
- name: install favarit favorite tools
  ansible.builtin.include_role:
    name: cmd_install
    tasks_from: goinstall
  loop:
    - "github.com/goreleaser/goreleaser@latest"
    - "github.com/fullstorydev/grpcurl/cmd/grpcurl@latest"
    - "github.com/google/ko@latest"
    - "github.com/kyoh86/richgo@latest"
    - "github.com/go-delve/delve/cmd/dlv@latest"
    - "github.com/xo/xo@latest"
