---
- name: Get rustup.sh
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/rustup.sh
    mode: 0755
- name: Install rustup
  command: "sh /tmp/rustup.sh -y --no-modify-path"
  args:
    creates: "{{ _user_home }}/.cargo/bin/rustup"
- name: Install current toolchain
  command: "{{ _user_home }}/.cargo/bin/rustup install {{ item }}"
  loop: [ nightly, stable ]
- name: Set restup default stable
  command: "{{ _user_home }}/.cargo/bin/rustup default stable"
- name: "add component {{ item }} stable"
  shell: "{{ _user_home }}/.cargo/bin/rustup component add {{ item }}"
  loop: [ rust-src, rustc-dev ]
- name: "add component {{ item }} nightly"
  shell: "{{ _user_home }}/.cargo/bin/rustup component add {{ item }} --toolchain=nightly"
  loop: [ rust-src, rustc-dev ]
- name: Insstall nighly packages
  command: "{{ _user_home }}/.cargo/bin/cargo +nightly install {{ item }}"
  args:
    creates: '{{ _user_home }}/.cargo/bin/{{ item }}'
  loop: "{{ _rust_nigtly_packages }}"
- name: Install rust tools
  command: "{{ _user_home }}/.cargo/bin/cargo install {{ item }}"
  args:
    creates: '{{ _user_home }}/.cargo/bin/{{ item }}'
  loop: "{{ _rust_packages }}"
