---
- ansible.builtin.get_url:
    url: "https://github.com/bufbuild/buf/releases/download/v{{ buf_version }}/buf-{{ ansible_system }}-{{ ansible_architecture }}"
    dest: "{{ buf_bin }}/buf"
    mode: '0755'
