---
- name: "Install packages (Debian)"
  apt:
    name: "{{ item }}"
    state: present
  loop: [ tcpdump, tshark, wireshark, nmap, whois, bind9-dnsutils, trace-cmd ]
  become: yes
  when: ansible_os_family == 'Debian'
- name: "Install packages (Ubuntu)"
  apt:
    name: "{{ item }}"
    state: present
  loop: [ termshark ]
  become: yes
  when: ansible_distribution == 'Ubuntu'
- name: "Install packages (Darwin)"
  homebrew:
    name: "{{ item }}"
    state: present
  loop: [ tcpdump, termshark, wireshark, nmap ]
  become: yes
  when: ansible_system == "Darwin"
