---
- hosts: all
  vars:
    _vim_dir: "{{ ansible_env.HOME }}/local"
    vim_dependent_pkgs:
      '20': [ lua5.3, libtolua-dev, luajit, libluajit-5.1-dev, luarocks ]
      '21': [ lua5.4, libtolua-dev, luajit, libluajit-5.1-dev, luarocks ]
  tasks:
  - name: Setup local tool directory
    file:
      path: "{{ item }}"
      state: directory
      mode: "0755"
    loop: [
      "{{ _vim_dir }}",
      "{{ _vim_dir }}/bin",
      "{{ _vim_dir }}/lib"
    ]
    # - name: Install lua apt libraries for Ubuntu (used by Vim)
    #   apt:
    #     name: "{{ item }}"
    #     state: present
    #   loop: "{{ vim_dependent_pkgs[ansible_distribution_major_version] }}"
    #   when: ansible_distribution == 'Ubuntu'
    #   become: yes
    # - name: Install apt lib for Vim
    #   apt:
    #     name: "{{ item }}"
    #     state: present
    #     update_cache: yes
    #     # loop: [ perl-base, perl-modules-5.30, libperl-dev, python3, python3-dev ]
    #   loop: [ python3, python3-dev ]
    #   become: yes
    # - name: install neovim from github
    # - name: Fetch vim source
    #   git:
    #     repo: https://github.com/vim/vim.git
    #     version: v8.2.2232
    #     dest: /tmp/vim.git
    # - name: Install Vim from source
    #   shell: |
    #     cd /tmp/vim.git
    #     ./configure \
    #       --prefix={{ _vim_dir }} \
    #       --enable-fail-if-missing \
    #       --enable-terminal \
    #       --enable-fontset --enable-cscope \
    #       --enable-perlinterp=dynamic \
    #       --enable-luainterp=yes \
    #       --with-luajit \
    #       --enable-python3interp=dynamic
    #       make install
    #   when: ansible_distribution == 'Ubuntu'
    #   args:
    #     chdir: /tmp/vim.git
    #     creates: '{{ _vim_dir }}/bin/vim'
  roles:
    - ansible_appliable
    - neovim
    - dev_utils
