---
- hosts: all
  vars:
    _vim_dir: "{{ ansible_env.HOME }}/local"
    _tmux_dir: "{{ ansible_env.HOME }}/local"
    _tmux_xpane_dir: "{{ ansible_env.HOME }}/local"
    _tmux_version: 3.1
    tmux_dependent_apt_pkgs:
      '16': [ "libevent-2.0-5", "libevent-dev", "libutf8proc1", "libutf8proc-dev" ]
      '18': [ "libevent-2.1-6", "libevent-dev", "libutf8proc2", "libutf8proc-dev" ]
      '20': [
        "libevent-2.1-7", "libevent-dev", "libutf8proc2", "libutf8proc-dev",
        "libevent-dev", "ncurses-dev", "build-essential", "bison", "pkg-config"
      ]
    vim_dependent_pkgs:
      '20': [ lua5.3, libtolua-dev, luajit, libluajit-5.1-dev, luarocks ]
      '21': [ lua5.4, libtolua-dev, luajit, libluajit-5.1-dev, luarocks ]
  tasks:
  - name: Setup local tool directory
    file:
      path: "{{ item }}"
      state: directory
      mode: "0755"
    loop: [
      "{{ _vim_dir }}",
      "{{ _vim_dir }}/bin",
      "{{ _vim_dir }}/lib"
    ]
    # - name: Install lua apt libraries for Ubuntu (used by Vim)
    #   apt:
    #     name: "{{ item }}"
    #     state: present
    #   loop: "{{ vim_dependent_pkgs[ansible_distribution_major_version] }}"
    #   when: ansible_distribution == 'Ubuntu'
    #   become: yes
    # - name: Install apt lib for Vim
    #   apt:
    #     name: "{{ item }}"
    #     state: present
    #     update_cache: yes
    #     # loop: [ perl-base, perl-modules-5.30, libperl-dev, python3, python3-dev ]
    #   loop: [ python3, python3-dev ]
    #   become: yes
    # - name: install neovim from github
    # - name: Fetch vim source
    #   git:
    #     repo: https://github.com/vim/vim.git
    #     version: v8.2.2232
    #     dest: /tmp/vim.git
    # - name: Install Vim from source
    #   shell: |
    #     cd /tmp/vim.git
    #     ./configure \
    #       --prefix={{ _vim_dir }} \
    #       --enable-fail-if-missing \
    #       --enable-terminal \
    #       --enable-fontset --enable-cscope \
    #       --enable-perlinterp=dynamic \
    #       --enable-luainterp=yes \
    #       --with-luajit \
    #       --enable-python3interp=dynamic
    #       make install
    #   when: ansible_distribution == 'Ubuntu'
    #   args:
    #     chdir: /tmp/vim.git
    #     creates: '{{ _vim_dir }}/bin/vim'
  - name: fetch tmux-xpanes
    get_url:
      url: https://raw.githubusercontent.com/greymd/tmux-xpanes/master/bin/xpanes
      dest: /tmp/xpanes
    when: ansible_distribution == 'Ubuntu'
  - name: install tmux-xpanes
    shell: |
      install -m 0755 xpanes {{ _tmux_xpane_dir }}/bin/xpanes
      echo "Ref: https://github.com/greymd/tmux-xpanes"
    args:
      chdir: /tmp/
    when: ansible_distribution == 'Ubuntu'
  - name: Install support tools
    apt:
      name: "{{ item }}"
    # loop: [ peco, direnv, fzf, tmux, tmuxinator, bat, jq, vim, neovim, exuberant-ctags, global ]
    loop: [ peco, direnv, fzf, tmux, tmuxinator, jq, vim, exuberant-ctags, global ]
    # when: ansible_distribution == 'Ubuntu'
    when: ansible_os_family == 'Debian'
    become: yes
  - name: Install support tools
    homebrew:
      name: "{{ item }}"
    loop: [ peco, direnv, fzf, tmux, tmuxinator, tmux-xpanes, bat, jq, vim, ctags, global ]
    when: ansible_system == 'Darwin'
    become: yes
  # TODO: Add docker with flag
