---
- hosts: all
  tasks:
  - name: "Install packages (Debian)"
    apt:
      name: "{{ item }}"
      state: present
    loop: [ tcpdump, tshark, termshark, wireshark ]
    become: yes
    when: ansible_os_family == 'Debian'
  - name: "Install packages (Darwin)"
    homebrew:
      name: "{{ item }}"
      state: present
    loop: [ tcpdump, termshark, wireshark ]
    become: yes
    when: ansible_system == "Darwin"
